#include<iostream>
#include<stdlib.h>
#include<limits.h>
#include <filesystem>

#include <fstream>

#include "EVRP.hpp"
#include "heuristic.hpp"
#include "stats.hpp"

using namespace std;

ofstream arquivo_run;
ofstream arquivo_evo_caminho;

/*initialiazes a run for your heuristic*/
void start_run(int r, char *problem_instance){

  srand(r);
  init_evals();
  init_current_best();
  cout << "Run: " << r << " with random seed " << r << endl;

  std::filesystem::path pasta_resultados = "resultados";
  std::filesystem::path caminho_diretorio = pasta_resultados / problem_instance; 
  
  string nome_foto = "analise_run_" + to_string(r) + ".txt";
  string nome_evo_caminho = "evo_caminho_run_" + to_string(r) + ".txt";
  std::filesystem::path caminho_foto = caminho_diretorio / nome_foto;
  std::filesystem::path caminho_evo_caminho = caminho_diretorio / nome_evo_caminho;

  std::error_code ec;
  std::filesystem::create_directories(caminho_diretorio, ec);
  if(ec){
    cerr << "Erro ao criar diretorio: " << ec.message() << "\n";
  }

  arquivo_run.open(caminho_foto.string());
  arquivo_evo_caminho.open(caminho_evo_caminho.string());
}

/*gets an observation of the run for your heuristic*/
void end_run(int r){

  get_mean(r-1,get_current_best()); //from stats.h
  cout << "End of run " << r << " with best solution quality " << get_current_best() << " total evaluations: " << get_evals()  << endl;
  cout << " " << endl;

  if(arquivo_run.is_open()){
      arquivo_run.close();
  }

  if(arquivo_evo_caminho.is_open()){
      arquivo_evo_caminho.close();
  }
}

/*sets the termination conidition for your heuristic*/
bool termination_condition(void) {
 
  bool flag; 
  if(get_evals() >= TERMINATION) 
    flag = true;
  else
    flag = false;

  return flag;
}


/****************************************************************/
/*                Main Function                                 */
/****************************************************************/
int main(int argc, char *argv[]) {

  int run;
  /*Step 1*/
  problem_instance = argv[1];       //pass the .evrp filename as an argument
  read_problem(problem_instance);   //Read EVRP from file from EVRP.h

  /*Step 2*/
  open_stats();//open text files to store the best values from the 20 runs stats.h

  for(run = 1; run <= MAX_TRIALS; run++){
      /*Step 3*/   
      start_run(run, problem_instance);
      //Initialize your heuristic here
      initialize_heuristic(); //heuristic.h 

      /*Step 4*/
      while(!termination_condition()){
        //Execute your heuristic
        run_heuristic(arquivo_run, arquivo_evo_caminho);  //heuristic.h
      }

      // printf("saiu da heuristica");
      //print_solution(best_sol->tour,best_sol->steps);
      //check_solution(best_sol->tour,best_sol->steps);
      /*Note that the solution generated by the random heuristic may not 
      be feasisble in terms of energy when check_solution is utilized. 
      The implementation is only for your reference*/
     /*Step 5*/
      end_run(run);  //store the best solution quality for each run
  }
  /*Step 6*/
  close_stats(); //close text files to calculate the mean result from the 20 runs stats.h


  //free memory
  free_stats();
  free_heuristic();
  free_EVRP();

  return 0;
}
